# Generated by Django 5.0.4 on 2025-06-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main_Kiyim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_img', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('tavsifi', models.CharField(max_length=100)),
                ('narhi', models.IntegerField()),
                ('skidkasi', models.IntegerField()),
            ],
        ),
    ]
