# Generated by Django 5.0.4 on 2025-06-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_kiyim',
            name='balandligi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='main_kiyim',
            name='beshinchi_xususiyati',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='main_kiyim',
            name='birinchi_xususiyati',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='main_kiyim',
            name='ikkinchi_xususiyati',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='main_kiyim',
            name='kilogrami',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='main_kiyim',
            name='kiyim_haqida',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='main_kiyim',
            name='oltinchi_xususiyati',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='main_kiyim',
            name='tortinchi_xususiyati',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='main_kiyim',
            name='uchunchi_xususiyati',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
