# Generated by Django 5.0.4 on 2025-06-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_main_kiyim_balandligi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_kiyim',
            name='qoshimcha_img',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
