# Generated by Django 5.0.4 on 2025-06-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_main_kiyim_qoshimcha_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main_kiyim',
            old_name='qoshimcha_img',
            new_name='birinchi_img',
        ),
        migrations.AddField(
            model_name='main_kiyim',
            name='ikkinchi_img',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
