# Generated by Django 5.0.4 on 2025-06-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_qoshimcha_img_main_kiyim_birinchi_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_kiyim',
            name='ikkinchi_varianat_img',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='main_kiyim',
            name='varianat_img',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
