# Generated by Django 5.0.4 on 2025-06-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_main_kiyim_birinchi_img_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='main_kiyim',
            options={'ordering': ['-id'], 'verbose_name': 'Asosiy kiyim', 'verbose_name_plural': 'Asosiy kiyimlar'},
        ),
        migrations.RemoveField(
            model_name='main_kiyim',
            name='ikkinchi_varianat_img',
        ),
        migrations.RemoveField(
            model_name='main_kiyim',
            name='varianat_img',
        ),
        migrations.AlterField(
            model_name='main_kiyim',
            name='balandligi',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Balandligi'),
        ),
        migrations.AlterField(
            model_name='main_kiyim',
            name='beshinchi_xususiyati',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='5-xususiyat'),
        ),
        migrations.AlterField(
            model_name='main_kiyim',
            name='birinchi_img',
            field=models.ImageField(blank=True, null=True, upload_to='kiyimlar/', verbose_name='1-rasm'),
        ),
        migrations.AlterField(
            model_name='main_kiyim',
            name='birinchi_xususiyati',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='1-xususiyat'),
        ),
        migrations.AlterField(
            model_name='main_kiyim',
            name='ikkinchi_img',
            field=models.ImageField(blank=True, null=True, upload_to='kiyimlar/', verbose_name='2-rasm'),
        ),
        migrations.AlterField(
            model_name='main_kiyim',
            name='ikkinchi_xususiyati',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='2-xususiyat'),
        ),
        migrations.AlterField(
            model_name='main_kiyim',
            name='kilogrami',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Og‘irligi'),
        ),
        migrations.AlterField(
            model_name='main_kiyim',
            name='kiyim_haqida',
            field=models.TextField(blank=True, null=True, verbose_name='Kiyim haqida'),
        ),
        migrations.AlterField(
            model_name='main_kiyim',
            name='main_img',
            field=models.ImageField(blank=True, help_text='Asosiy ko‘rinish rasmi', null=True, upload_to='kiyimlar/', verbose_name='Asosiy rasm'),
        ),
        migrations.AlterField(
            model_name='main_kiyim',
            name='narhi',
            field=models.PositiveIntegerField(verbose_name='Narxi (so‘m)'),
        ),
        migrations.AlterField(
            model_name='main_kiyim',
            name='oltinchi_xususiyati',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='6-xususiyat'),
        ),
        migrations.AlterField(
            model_name='main_kiyim',
            name='skidkasi',
            field=models.PositiveIntegerField(help_text='0 agar chegirma bo‘lmasa', verbose_name='Chegirma (%)'),
        ),
        migrations.AlterField(
            model_name='main_kiyim',
            name='tavsifi',
            field=models.CharField(max_length=100, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='main_kiyim',
            name='tortinchi_xususiyati',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='4-xususiyat'),
        ),
        migrations.AlterField(
            model_name='main_kiyim',
            name='uchunchi_xususiyati',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='3-xususiyat'),
        ),
    ]
