# Generated by Django 5.0.4 on 2025-06-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_main_kiyim_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_kiyim',
            name='jinsi',
            field=models.CharField(choices=[('qiz', 'Qiz bola'), ('ogil', 'O‘g‘il bola')], default='qiz', help_text='Qiz bola yoki o‘g‘il bola uchun', max_length=5, verbose_name='Jinsi'),
        ),
        migrations.AlterField(
            model_name='main_kiyim',
            name='balandligi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='main_kiyim',
            name='beshinchi_xususiyati',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='main_kiyim',
            name='birinchi_img',
            field=models.ImageField(blank=True, null=True, upload_to='kiyimlar/'),
        ),
        migrations.AlterField(
            model_name='main_kiyim',
            name='birinchi_xususiyati',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='main_kiyim',
            name='ikkinchi_img',
            field=models.ImageField(blank=True, null=True, upload_to='kiyimlar/'),
        ),
        migrations.AlterField(
            model_name='main_kiyim',
            name='ikkinchi_xususiyati',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='main_kiyim',
            name='kilogrami',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='main_kiyim',
            name='kiyim_haqida',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='main_kiyim',
            name='main_img',
            field=models.ImageField(blank=True, null=True, upload_to='kiyimlar/'),
        ),
        migrations.AlterField(
            model_name='main_kiyim',
            name='narhi',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='main_kiyim',
            name='oltinchi_xususiyati',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='main_kiyim',
            name='skidkasi',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='main_kiyim',
            name='tavsifi',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='main_kiyim',
            name='tortinchi_xususiyati',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='main_kiyim',
            name='uchunchi_xususiyati',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
