# Generated by Django 5.0.4 on 2025-06-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_main_kiyim_jinsi_alter_main_kiyim_balandligi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_kiyim',
            name='skidkasi',
            field=models.PositiveIntegerField(blank=True, help_text="Chegirma foizi, agar yo'q bo‘lsa bo‘sh qoldiring", null=True, verbose_name='Chegirma (%)'),
        ),
    ]
