# Generated by Django 5.0.4 on 2025-06-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_main_kiyim_skidkasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_kiyim',
            name='yoshi',
            field=models.CharField(blank=True, choices=[('1', '1 oylik'), ('2', '2 oylik'), ('3', '3 oylik'), ('4', '4 oylik'), ('5', '5 oylik'), ('6', '6 oylik'), ('7', '7 oylik'), ('8', '8 oylik'), ('9', '9 oylik')], max_length=2, null=True, verbose_name='Bolalar yoshi'),
        ),
    ]
