# Generated by Django 5.0.4 on 2025-06-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_main_kiyim_yoshi'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_kiyim',
            name='m3_balandligi',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='3M balandligi'),
        ),
        migrations.AddField(
            model_name='main_kiyim',
            name='m3_kilogrami',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='3M kilogrami'),
        ),
        migrations.AddField(
            model_name='main_kiyim',
            name='m6_balandligi',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='6M balandligi'),
        ),
        migrations.AddField(
            model_name='main_kiyim',
            name='m6_kilogrami',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='6M kilogrami'),
        ),
        migrations.AddField(
            model_name='main_kiyim',
            name='m9_balandligi',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='9M balandligi'),
        ),
        migrations.AddField(
            model_name='main_kiyim',
            name='m9_kilogrami',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='9M kilogrami'),
        ),
        migrations.AddField(
            model_name='main_kiyim',
            name='nb_balandligi',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='NB balandligi'),
        ),
        migrations.AddField(
            model_name='main_kiyim',
            name='nb_kilogrami',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='NB kilogrami'),
        ),
        migrations.AddField(
            model_name='main_kiyim',
            name='pre_balandligi',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PRE balandligi'),
        ),
        migrations.AddField(
            model_name='main_kiyim',
            name='pre_kilogrami',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PRE kilogrami'),
        ),
    ]
