# Generated by Django 5.0.4 on 2025-06-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_main_kiyim_m3_balandligi_main_kiyim_m3_kilogrami_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_kiyim',
            name='variant',
            field=models.CharField(blank=True, choices=[('PRE', 'PRE'), ('NB', 'NB'), ('3M', '3M'), ('6M', '6M'), ('9M', '9M')], max_length=3, null=True),
        ),
    ]
