# Generated by Django 5.0.4 on 2025-06-28 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_main_kiyim_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main_kiyim',
            name='variant',
        ),
    ]
