# Generated by Django 5.0.4 on 2025-06-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_main_kiyim_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_kiyim',
            name='yoshi',
            field=models.CharField(blank=True, choices=[('1', '1 oylik'), ('2', '2 oylik'), ('3', '3 oylik'), ('4', '4 oylik'), ('5', '5 oylik'), ('6', '6 oylik'), ('7', '7 oylik'), ('8', '8 oylik'), ('9', '9 oylik'), ('9', '9 oylik'), ('10', '10 oylik'), ('11', '11 oylik'), ('12', '12 oylik'), ('13', '1 yosh'), ('14', '2 yosh'), ('15', '3 yosh'), ('16', '4 yosh')], max_length=2, null=True, verbose_name='Bolalar yoshi'),
        ),
    ]
