# Generated by Django 5.0.4 on 2025-06-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_main_kiyim_yoshi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_kiyim',
            name='m3_balandligi',
            field=models.CharField(blank=True, choices=[('40', '40 sm'), ('45', '45 sm'), ('50', '50 sm'), ('55', '55 sm'), ('60', '60 sm'), ('65', '65 sm'), ('70', '70 sm')], max_length=50, null=True, verbose_name='3M balandligi'),
        ),
        migrations.AlterField(
            model_name='main_kiyim',
            name='m3_kilogrami',
            field=models.CharField(blank=True, choices=[('2', '2 kg'), ('2.5', '2.5 kg'), ('3', '3 kg'), ('3.5', '3.5 kg'), ('4', '4 kg'), ('4.5', '4.5 kg'), ('5', '5 kg')], max_length=50, null=True, verbose_name='3M kilogrami'),
        ),
        migrations.AlterField(
            model_name='main_kiyim',
            name='m6_balandligi',
            field=models.CharField(blank=True, choices=[('40', '40 sm'), ('45', '45 sm'), ('50', '50 sm'), ('55', '55 sm'), ('60', '60 sm'), ('65', '65 sm'), ('70', '70 sm')], max_length=50, null=True, verbose_name='6M balandligi'),
        ),
        migrations.AlterField(
            model_name='main_kiyim',
            name='m6_kilogrami',
            field=models.CharField(blank=True, choices=[('2', '2 kg'), ('2.5', '2.5 kg'), ('3', '3 kg'), ('3.5', '3.5 kg'), ('4', '4 kg'), ('4.5', '4.5 kg'), ('5', '5 kg')], max_length=50, null=True, verbose_name='6M kilogrami'),
        ),
        migrations.AlterField(
            model_name='main_kiyim',
            name='m9_balandligi',
            field=models.CharField(blank=True, choices=[('40', '40 sm'), ('45', '45 sm'), ('50', '50 sm'), ('55', '55 sm'), ('60', '60 sm'), ('65', '65 sm'), ('70', '70 sm')], max_length=50, null=True, verbose_name='9M balandligi'),
        ),
        migrations.AlterField(
            model_name='main_kiyim',
            name='m9_kilogrami',
            field=models.CharField(blank=True, choices=[('2', '2 kg'), ('2.5', '2.5 kg'), ('3', '3 kg'), ('3.5', '3.5 kg'), ('4', '4 kg'), ('4.5', '4.5 kg'), ('5', '5 kg')], max_length=50, null=True, verbose_name='9M kilogrami'),
        ),
        migrations.AlterField(
            model_name='main_kiyim',
            name='nb_balandligi',
            field=models.CharField(blank=True, choices=[('40', '40 sm'), ('45', '45 sm'), ('50', '50 sm'), ('55', '55 sm'), ('60', '60 sm'), ('65', '65 sm'), ('70', '70 sm')], max_length=50, null=True, verbose_name='NB balandligi'),
        ),
        migrations.AlterField(
            model_name='main_kiyim',
            name='nb_kilogrami',
            field=models.CharField(blank=True, choices=[('2', '2 kg'), ('2.5', '2.5 kg'), ('3', '3 kg'), ('3.5', '3.5 kg'), ('4', '4 kg'), ('4.5', '4.5 kg'), ('5', '5 kg')], max_length=50, null=True, verbose_name='NB kilogrami'),
        ),
        migrations.AlterField(
            model_name='main_kiyim',
            name='pre_balandligi',
            field=models.CharField(blank=True, choices=[('40', '40 sm'), ('45', '45 sm'), ('50', '50 sm'), ('55', '55 sm'), ('60', '60 sm'), ('65', '65 sm'), ('70', '70 sm')], max_length=50, null=True, verbose_name='PRE balandligi'),
        ),
        migrations.AlterField(
            model_name='main_kiyim',
            name='pre_kilogrami',
            field=models.CharField(blank=True, choices=[('2', '2 kg'), ('2.5', '2.5 kg'), ('3', '3 kg'), ('3.5', '3.5 kg'), ('4', '4 kg'), ('4.5', '4.5 kg'), ('5', '5 kg')], max_length=50, null=True, verbose_name='PRE kilogrami'),
        ),
    ]
